#' Generate sanitized proportions that satisfy (epsilon,delta)-DP
#'
#' @param hist.df a data.frame of the counts for the number of occurrences of a category (or combination of categories) which is column \code{hist.df$Freq}vector of continuous values to be split into bins
#' @param epsilon a positive privacy parameter value
#' @param delta a non-negative value for a privacy parameter. If \code{nrow(hist.df)<=}
#' @return a data.frame which is the hist.df with column \code{hist.df$san.prop} which is a sanitized proportion of the data that is in a bin which is generated by a Laplace mechanism satisfying (\code{epsilon},\code{delta})-differential privacy.
#'
#' @examples
#' freq.df=multivariate_histogram(mtcars[,2:4],continuous.vars=c("disp","hp"),num.bin=3)
#' dp_perturbed_hist(freq.df,0.9,delta=0.01)
#'
#' @references
#' When \code{delta==0} or \code{nrow(hist.df)<=2/delta}, perturbed histogram algorithm is from:
#' Karwa, V. and Vadhan, S. (2017). Finite sample differentially private confidence intervals.
#'
#' When \code{delta>0} and \code{nrow(hist.df)>2/delta}, perturbed histogram algorithm is from:
#' Bun, M., Nissim, K., and Stemmer, U. (2016). Simultaneous private learning of multiple
#' concepts. In Proceedings of the 2016 ACM Conference on Innovations in Theoretical Computer Science,
#' ITCS ’16, page 369–380, New York, NY, USA. Association for Computing Machinery.
#'
#'
#' @family syntheticData
#' @importFrom VGAM rlaplace
#' @noRd


dp_perturbed_hist<-function(hist.df,epsilon,delta=0,possible.combos=NULL){

 # warn.message=NULL
  #hist.df=hist.df[hist.df$Freq>0,,drop=F] #remove bins with 0 counts
  #nobs=base::sum(hist.df$Freq,na.rm=T) #number of observations
  #if(nobs<10){
  #  message(paste("The number of histogram observations is less then 10:",nobs,"\n"))
  #}
  #if using delta>0, and number of bins is high enough

  gen_unrealized=function(san.props,missing.combos,threshold,epsilon,nobs,rseed=NA){
    if(is.na(rseed)==FALSE){
      set.seed(rseed)
    }
    sc.param=1/(nobs*epsilon)
    rcount.above.threshold=rbinom(1,missing.combos,threshold)
    sumexp=rgamma(1,rcount.above.threshold,1/sc.param)
    p.select.unobserved=sumexp/(sum(san.props)+sumexp)
    rcount.select.unobserved=rbinom(1,nobs,p.select.unobserved)
    #rcount.select.observed=nobs-rcount.select.unobserved
    message(paste("Number of unobserved rows selected is:",rcount.select.unobserved))
    return(list(rcount.select.unobserved,sum(san.props)+sumexp))
  }


  nobs=sum(hist.df$Freq,na.rm=T)
  num.bins=base::nrow(hist.df) #number of bins
  hist.df$san.prop=hist.df$Freq/nobs
  #add laplace noise
  hist.df$san.prop=(hist.df$san.prop+
                      VGAM::rlaplace(num.bins,0,scale=1/(nobs*epsilon)))

  if(is.null(possible.combos)==TRUE){
    #message("No possible.combos provided. It is assumed all potential combinations of variables are represented in hist.df.")
    #if(possible.combos==base::nrow(hist.df)){
    if((delta>0)&(base::nrow(hist.df)>(2/delta))){ #use Bun et al. 2016
      threshold=((2*base::log(2/delta))/(epsilon/nobs))+(1/nobs)
    }else{ #pure-DP and low number of bins don't use a threshold
      threshold=0
    }
    hist.df$san.prop=base::pmax(hist.df$san.prop,threshold)
    #hist.df$san.prop=hist.df$san.prop/sum(hist.df$san.prop)
    count.unobs.rows=0
    used.sanprop.add=F
  }else{
    used.sanprop.add=T
    missing.combos=possible.combos-nrow(hist.df)
    if((delta>0)&(possible.combos>(2/delta))){ #use Bun et al. 2016
      threshold=((2*base::log(2/delta))/(epsilon/nobs))+(1/nobs)
    }else{ #pure-DP and low number of bins don't use a threshold
      threshold=0
    }
    hist.df$san.prop=base::pmax(hist.df$san.prop,threshold)
    sc.param=1/(nobs*epsilon)
    out=gen_unrealized(san.props=hist.df$san.prop, missing.combos = missing.combos,
                                       threshold=threshold,nobs=nobs,epsilon=epsilon)
    count.unobs.rows=out[[1]]
    normalizer=out[[1]]
  }

  if(used.sanprop.add==TRUE){
    #print("in used.sanprop.add==TRUE")
    #total=(sum(hist.df$san.prop)+sum(sanprop.zero.to.add))
    #hist.df$san.prop=hist.df$san.prop/total #normalize
    #sanprop.zero.to.add=sanprop.zero.to.add/total
    return(list("hist.df"=hist.df,"count.unobs.rows.sampled"=count.unobs.rows,"normalizing constant"=normalizer))
  }else{
    return(hist.df)
  }
}





# gen_unrealized=function(missing.combos,threshold,sc.param,rseed=NA){
#   if(is.na(rseed)==FALSE){
#     set.seed(rseed)
#   }
#   # count.threshold=nobs*threshold
#   # if((1/epsilon)<1){
#   #   message("epsilon is such that the discrete laplace mechanism can be used")
#   #   p.above=extraDistr::::pdlaplace(count.threshold,mu=0, scale=(1/epsilon),lower.tail=F)
#   # }else{
#   #   message("epsilon is such that the discrete laplace mechanism can not be used")
#   #   p.above=extraDistr::::pdlaplace(count.threshold,mu=0, scale=(1/epsilon),lower.tail=F)
#   # }
#   p.above=1-VGAM::plaplace(threshold,scale=sc.param,lower.tail = T)
#   rcount.above.threshold=rbinom(1,missing.combos,p.above)
#   print(paste("The rcount is",rcount.above.threshold,"and missing combos is",missing.combos))
#   if(rcount.above.threshold>0){
#     unif.prob1=stats::runif(rcount.above.threshold%/%4,p.above,1)
#     unif.prob2=stats::runif(rcount.above.threshold%/%4,p.above,1)
#     unif.prob3=stats::runif(rcount.above.threshold%/%4,p.above,1)
#     unif.prob4=stats::runif(rcount.above.threshold-(3*(rcount.above.threshold%/%4)),p.above,1)
#     san.prop1=VGAM::qlaplace(unif.prob1,0,scale=sc.param,lower.tail=T)
#     san.prop2=VGAM::qlaplace(unif.prob2,0,scale=sc.param,lower.tail=T)
#     san.prop3=VGAM::qlaplace(unif.prob3,0,scale=sc.param,lower.tail=T)
#     san.prop4=VGAM::qlaplace(unif.prob4,0,scale=sc.param,lower.tail=T)
#
#     return(c(san.prop1,san.prop2,san.prop3,san.prop4))
#   }else{
#     return(NULL)
#   }
# }
#


